In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
list= [1,2,3,4]

In [5]:
list

[1, 2, 3, 4]

In [6]:
#Listeden array yapma
b = np.array(list)

In [7]:
b

array([1, 2, 3, 4])

In [8]:
type(a)

numpy.ndarray

In [9]:
type(list)

list

In [10]:
#tuple dan array yapma
t1 = (4,5,6,7,8)

In [11]:
f = np.array(t1)

In [12]:
type(f)

numpy.ndarray

In [13]:
f

array([4, 5, 6, 7, 8])

In [14]:
for i in f:
    print(i)

4
5
6
7
8


In [15]:
for i in f:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [16]:
#Otomatik olarak değişir değer tiplerini floatnp. veri tipine dönüştürek işlemi gerçekleştiriyor.
a = np.array([1.,2.,3,5.6,6.9])

In [17]:
for i in a :
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [18]:
#ZEROS and ONES
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [20]:
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones(6)*22

array([22., 22., 22., 22., 22., 22.])

In [23]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [24]:
#Çok boyutlu arrayler

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0,3,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
np.random.rand(5)#0 ile 1 arası üretir

array([0.2998169 , 0.55703256, 0.45766282, 0.85044682, 0.95166336])

In [31]:
np.random.randint(0,10)

8

In [32]:
np.random.randint(0,10,(3,4))

array([[1, 3, 0, 3],
       [7, 4, 1, 1],
       [4, 8, 9, 8]])

In [33]:
a = np.random.randint(1,10,size=10)
a

array([9, 4, 2, 4, 2, 3, 4, 9, 9, 3])

In [34]:
a.ndim#boyut sayısı

1

In [35]:
a.shape

(10,)

In [36]:
b = np.random.randint(1,10,(3,4))

In [37]:
b.size

12

In [38]:
b.shape

(3, 4)

In [39]:
a.size

10

In [40]:
a.dtype

dtype('int32')

In [41]:
a = np.arange(1,10).reshape(3,3)

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [45]:
np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a1 = ([1,2,3],[4,5,6])
a2 = ([10,20,30],[40,50,60])

In [47]:
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [48]:
a1

([1, 2, 3], [4, 5, 6])

In [49]:
a2

([10, 20, 30], [40, 50, 60])

In [50]:
a1 = np.array(([1,2,3],[4,5,6]))
a2 = np.array(([10,20,30]))

In [51]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a2

array([10, 20, 30])

In [53]:
#vstack

In [54]:
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [55]:
x = np.array(([1,2,3],[4,5,6]))
y = np.array(([7,8],[10,20]))

In [56]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
y

array([[ 7,  8],
       [10, 20]])

In [58]:
np.hstack([x,y])

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6, 10, 20]])

In [59]:
a = np.random.randint(1,10,12)

In [60]:
a

array([1, 8, 7, 8, 5, 3, 4, 1, 9, 1, 1, 3])

In [61]:
np.split(a,[15])

[array([1, 8, 7, 8, 5, 3, 4, 1, 9, 1, 1, 3]), array([], dtype=int32)]

In [62]:
np.split(a,[5,7])

[array([1, 8, 7, 8, 5]), array([3, 4]), array([1, 9, 1, 1, 3])]

In [63]:
np.random.randint(1,20,12)

array([13,  3, 16,  8, 19,  1,  6,  5,  2,  1, 17,  8])

In [64]:
a

array([1, 8, 7, 8, 5, 3, 4, 1, 9, 1, 1, 3])

In [65]:
a[4]

5

In [66]:
b = np.random.randint(12,size=(3,4))

In [67]:
b

array([[ 5,  8,  9,  5],
       [ 4,  1, 10, 11],
       [ 1,  9, 11, 11]])

In [68]:
b[1,1]

1

In [69]:
b[1][1]

1

In [70]:
b = np.random.randint(20,size=(5,4))

In [71]:
b

array([[11, 13,  2, 11],
       [ 7,  3,  8, 11],
       [19,  2, 14, 16],
       [ 3,  5, 12,  9],
       [17,  8,  6,  6]])

In [72]:
b[2][1:4]

array([ 2, 14, 16])

In [73]:
b[2,1:]

array([ 2, 14, 16])

In [74]:
b = np.random.randint(50, size = (10,5))

In [75]:
b

array([[38, 21,  8, 22, 42],
       [47, 31, 21, 49, 48],
       [18, 35, 44, 36,  6],
       [33, 10, 37, 43, 44],
       [38, 23, 35, 26,  7],
       [27, 25,  9, 35, 39],
       [37, 39, 26, 44, 46],
       [ 5, 49, 38, 33,  2],
       [36, 22, 23,  6, 29],
       [31, 17, 31, 45, 28]])

In [76]:
b[4:6,1:3]

array([[23, 35],
       [25,  9]])

In [77]:
b = np.random.randint(0,20,10)

In [78]:
b

array([11,  5,  0,  3, 10,  2, 15, 16,  8,  2])

In [79]:
b[3] = 15

In [80]:
b

array([11,  5,  0, 15, 10,  2, 15, 16,  8,  2])

In [81]:
list1 = [1,2,3,4,5,6]
list2 = list1

In [82]:
list1

[1, 2, 3, 4, 5, 6]

In [83]:
list2

[1, 2, 3, 4, 5, 6]

In [84]:
list1[1]=10

In [85]:
list1

[1, 10, 3, 4, 5, 6]

In [86]:
list2

[1, 10, 3, 4, 5, 6]

In [87]:
list2 = np.copy(list1)

In [88]:
list2

array([ 1, 10,  3,  4,  5,  6])

In [89]:
list1[1]=546

In [90]:
list1

[1, 546, 3, 4, 5, 6]

In [91]:
list2

array([ 1, 10,  3,  4,  5,  6])

In [92]:
a = np.arange(1,8)

In [93]:
a>5

array([False, False, False, False, False,  True,  True])

In [94]:
b = np.random.randint(50,size=(10,5))

In [95]:
np.sum(b>5)

44

In [96]:
#1
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [97]:
#2
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [99]:
#3
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [100]:
#4
np.full([4,5],8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [102]:
#5
np.arange(20,50,3)

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [104]:
#6
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
#7
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [108]:
#8
np.random.randn(3,4)

array([[-0.43771396,  0.95954155, -1.41679196, -0.30029093],
       [-1.49135952,  0.38222061, -0.05232089, -0.43425722],
       [ 0.57661952,  1.41232526,  0.9507192 , -0.63049845]])

In [110]:
#9
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [113]:
a=np.random.rand(10)


In [115]:
a

array([0.42481788, 0.98971723, 0.45637156, 0.56153825, 0.05168007,
       0.54084541, 0.43564588, 0.91795809, 0.71541021, 0.07319645])

In [116]:
max(a)

0.98971723024888

In [117]:
min(a)

0.051680071099994174

In [119]:
a = np.random.randint(1,30,20).reshape(5,4)

In [120]:
a

array([[ 1,  7, 24, 27],
       [ 1,  8,  8, 27],
       [13, 22, 24, 17],
       [24, 27, 23,  4],
       [23,  5, 19, 15]])

In [121]:
a[1,:]

array([ 1,  8,  8, 27])

In [122]:
a[2,3]

17

In [123]:
a[:,3]

array([27, 27, 17,  4, 15])

In [124]:
a=np.arange(1,7).reshape(2,3)

In [125]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [126]:
a=np.random.rand(6)
a*5


array([2.09178358e-03, 2.15760646e-01, 1.64413902e+00, 2.83808642e+00,
       1.51810651e+00, 3.29361940e+00])

In [127]:
sum(a)
2.7341623982675354


2.7341623982675354

In [128]:
np.median(a)
0.6037817371739695


0.6037817371739695

In [129]:
np.std(a)
0.24551707547157878


0.24551707547157878